services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - log-ingestor

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server=kafka:9092", "--list" ]
      start_period: 15s
      interval: 10s
    networks:
      - log-ingestor
    hostname: kafka

  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8083:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=localhost:9092
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=connect-cluster
      - CONNECT_CONFIG_STORAGE_TOPIC=docker-connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=docker-connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=docker-connect-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka
      - CONNECT_PLUGIN_PATH=/usr/share/java
    networks:
      - log-ingestor

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - log-ingestor

  server:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
      - zookeeper
      - kafka-connect
    ports:
      - 8080:8080
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=error_logs
      - KAFKA_GROUP_ID=log_group
      - MONGODB_URI=mongodb://mongo:27017
      - COLLECTION_NAME=errors
      - DB_NAME=ingester
      - PORT=8080
    networks:
      - log-ingestor

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
      - zookeeper
      - kafka-connect
      - mongo
      - server
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=error_logs
      - KAFKA_GROUP_ID=log_group
      - MONGODB_URI=mongodb://mongo:27017
      - COLLECTION_NAME=errors
      - DB_NAME=ingester
      - PORT=8080
    networks:
      - log-ingestor

volumes:
  mongo-data:


networks:
  log-ingestor:
    driver: bridge
